name: build packages

on:
  workflow_dispatch:
  push:
    paths:
      - "pkgs"
      - "**.lock"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: "Build packages and upload to cache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: frahz-pkgs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build packages
        run: |
          nix run \
            github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --option accept-flake-config true \
            --flake '.#hydraJobs.x86_64-linux'
