name: build packages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
  workflow_run:
    workflows: [ "Bump Flake Inputs" ]
    types:
      - completed

jobs:
  build:
    name: "Build packages and upload to cache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: frahz-pkgs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build packages
        run: |
          nix run \
            github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --option accept-flake-config true \
            --flake '.#hydraJobs.x86_64-linux'
